version: '3.8'

services:
  rodizio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rodizio-organistas
    expose:
      - "8080"
    volumes:
      # Volume para persistência do banco de dados JSON
      - ./data:/app/data
      # Volume para desenvolvimento (opcional - comente em produção)
      # - ./templates:/app/templates
      # - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - TZ=America/Sao_Paulo
    restart: unless-stopped
    networks:
      - rodizio-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health').read()"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: rodizio-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - rodizio-app
    restart: unless-stopped
    networks:
      - rodizio-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: rodizio-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  rodizio-network:
    driver: bridge

volumes:
  rodizio-data:
    driver: local
